spring:
  application:
    name: company-service
  datasource:
    url: jdbc:mysql://backend1.cdtkhh7bqkna.ap-northeast-2.rds.amazonaws.com:3306/backend1
    username: admin
    password: iceamericano
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #create -> update
    show-sql: true
    properties:
      hibernate:
        format_sql:true
  main:
    web-application-type: servlet
    servlet:
      multipart:
        enabled: true
        max-file-size: 50MB
        max-request-size: 50MB

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 15.165.249.107
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.124.61.210:8761/eureka

management:
  endpoint:
    web:
      exposure:
        include: "*"
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: iceamericano-company
